---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/AccessorMethodName:
        enabled: false
  coffeelint:
    enabled: true
  scsslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.coffee"
  - "**.scss"
exclude_paths:
- config/**/*
- db/**/*
- spec/**/*
- vendor/**/*
- Capfile
- Gemfile*
- public/**/*
- bin/**/*
- config.ru
