image:
  name: ruby:2.5.0

services:
  - name: redis:3.2.7
  - name: postgres:9.6-alpine
    alias: postgres

cache:
  paths:
    - vendor/bundle

variables:
  BUNDLE_PATH: vendor/bundle
  DISABLE_SPRING: 1

before_script:
  - sudo apt-get update
  - sudo apt-get install -y postgresql-client
  - sudo apt-get install -y nodejs
  - bundle install --jobs 4 --retry 3
  - RAILS_ENV=test bundle exec rake db:create db:migrate

stages:
  - test

Tests:
  stage: test
  script:
    - RAILS_ENV=test RAILS_DISABLE_TEST_LOG=true bundle exec rspec spec/ --tag '~skip_ci' --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
