Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/AccessorMethodName:
  enabled: false
Style/MethodDefParentheses:
  enabled: false
Metrics/LineLength:
  Max: 120
