web:
  build: .
  command: [bundle, exec, puma, -C, config/puma.rb]
  environment:
    - RACK_ENV=production
    - RAILS_ENV=production
    - ASSET_HOST=temp
    - MAILER_HOST=temp
  ports:
    - '80:3000'
    - '443:3000'
  volumes:
    - .:/app
worker:
  build: .
  command: [bundle, exec, sidekiq]
  volumes:
    - '.:/app'
