version: "3.8"
services:
  web: &web
    env_file: 
      - .env
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis-db:6379
      - DATABASE_URL=postgres://root:password@postgres-db/qae_development
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-db:
        condition: service_started
    command: /rails/bin/rails server
    entrypoint: ["/rails/bin/docker-entrypoint"]
    volumes:
      - .:/rails:cached
    ports:
      - "3000:3000"
  
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qae_development
    volumes:
      - ./tmp/postgres-db:/var/lib/postgresql/data
      - ./init-hstore.sql:/docker-entrypoint-initdb.d/init-hstore.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d qae_development"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis-db:
    image: redis
    ports:
      - "6379:6379"

  sidekiq:
    <<: *web
    command: bundle exec sidekiq
    ports: []
