default: &defaults
  # Your Push API Key, it is possible to set this dynamically using ERB. Required
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"

  # Your app's name as reported on AppSignal.com. Required
  name: "QAE"

  revision: "<%= ENV['APP_REVISION'] %>"

  # Add default instrumentation of net/http. Default: true
  # instrument_net_http: true

  # Skip session data, if it contains private information. Default: false
  # skip_session_data: true

  # Ignore these errors (Optional)
  #ignore_errors:
  #  - SystemExit

  # Ignore these actions, used by our Loadbalancer. Optional
  ignore_actions:
    - Healthcheck::HealthchecksController#check

  ignore_errors:
    - ActionController::InvalidAuthenticityToken

  # Enable allocation tracking for memory metrics. Default: true
  enable_allocation_tracking: true

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
development:
  <<: *defaults
  active: true
  # Enable more logging in the `appsignal.log` file. Optional
  debug: true

production:
  <<: *defaults
  # Configure AppSignal to be active for this environment. Required
  active: true
  running_in_container: true

