default: &default
  adapter: postgresql
  encoding: utf8

development: &development
  <<: *default
  database: qae_development
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: postgres
  password: password

test:
  <<: *development
  database: qae_test

production:
  <<: *default
  url: <%= PaasResolver.pgsql_uri %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
